import { useEffect, useState } from "react"

/**
 * This component is used to display the version of the app. Only runs on client.
 * It fetches the version from the version.json file in the public directory.
 * The version file is generated by the prebuild script.
 */
export default function Version() {
	const [version, setVersion] = useState<{ sha: string } | null>(null)

	useEffect(() => {
		fetch("/version.json")
			.then((res) => res.json())
			.then(setVersion)
	}, [])

	return (
		<div className="text-center text-gray-500 text-sm">
			Version: {version?.sha}
		</div>
	)
}
