/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToastTestRouteImport } from './routes/toast-test'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ArchivedRouteImport } from './routes/archived'
import { Route as IndexRouteImport } from './routes/index'

const ToastTestRoute = ToastTestRouteImport.update({
  id: '/toast-test',
  path: '/toast-test',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchivedRoute = ArchivedRouteImport.update({
  id: '/archived',
  path: '/archived',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/archived': typeof ArchivedRoute
  '/login': typeof LoginRoute
  '/toast-test': typeof ToastTestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/archived': typeof ArchivedRoute
  '/login': typeof LoginRoute
  '/toast-test': typeof ToastTestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/archived': typeof ArchivedRoute
  '/login': typeof LoginRoute
  '/toast-test': typeof ToastTestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/archived' | '/login' | '/toast-test'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/archived' | '/login' | '/toast-test'
  id: '__root__' | '/' | '/archived' | '/login' | '/toast-test'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchivedRoute: typeof ArchivedRoute
  LoginRoute: typeof LoginRoute
  ToastTestRoute: typeof ToastTestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/toast-test': {
      id: '/toast-test'
      path: '/toast-test'
      fullPath: '/toast-test'
      preLoaderRoute: typeof ToastTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archived': {
      id: '/archived'
      path: '/archived'
      fullPath: '/archived'
      preLoaderRoute: typeof ArchivedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchivedRoute: ArchivedRoute,
  LoginRoute: LoginRoute,
  ToastTestRoute: ToastTestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
